# Generated by Django 4.0.3 on 2022-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_materials_product_available_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_materials',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
    ]
