# Generated by Django 4.0.3 on 2022-03-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_product_materials_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product_materials',
            name='available',
        ),
    ]
